
encoding_model: cl100k_base

workflows: ["create_communities","create_final_text_units","create_community_reports","generate_text_embeddings"]

cluster_graph:
  max_cluster_size: 10
  use_lcc: false

storage:
  type: file
  base_dir: "artifacts"

completion_models:
  default_completion_model:
    model_provider: openai
    model: qwen/qwen3-next-80b-a3b-instruct
    api_base: "https://integrate.api.nvidia.com/v1"
    api_key: "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"
    raw_completion_model: true

embedding_models:
  default_embedding_model:
    model_provider: openai
    model: "nvidia/nv-embed-v1"
    api_base: "https://integrate.api.nvidia.com/v1"
    api_key: "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"
    call_args:
        encoding_format: float
